= Gunjan Patel
:icons: font
:docinfo: private-head

// Google Analytics
ifdef::backend-html5[]
++++
include::ga.html[]
++++
endif::[]

// Crosslinking
ifdef::backend-pdf[]
TIP: This resume is being regularly updated. An up to date copy is available in HTML at
     https://www.actuallygunjan.com[www.actuallygunjan.com][the same website] or via downloadable PDF on .
endif::[]

ifdef::backend-html5[]
TIP: This resume is being regularly updated. However a printable PDF copy of the current version of this resume can be
     found https://www.actuallygunjan.com/media/pdf/resume.pdf[attached to this website].
endif::[]

NOTE: Looking to embark myself on Web3 (or whatever you'd like to call it) - Crypto stuff
I may not be a stand-up comedian, but I am a stand-out software engineer.

== Personal Information

[cols="3,8,3,8"]
|===
h| Email     | mailto:deago.gunjan@gmail.com[deago.gunjan@gmail.com]                                  h| GitHub    | https://www.github.com/actuallygunjan/[@actuallygunjan]
h| Telephone |  +49 174 2585884                                                                     h| LinkedIn  | https://www.linkedin.com/in/actuallygunjan/[actuallygunjan]
h| Website   | https://github.com/actuallygunjan/actuallygunjan.github.io[www.actuallygunjan.com]     h| Twitter   | https://www.twitter.com/@actuallygunjan[@actuallygunjan]
|===

== Professional Background

=== N26
==== Sr. Software Engineer (2022 - Present)
Building KYC backends for N26, integrating systems with multiple KYC providers for various markets.
Building a self-organizing team, partially fulfilling the role of engineering manager

=== Zalando SE
==== Sr. Software Engineer (2020 - 2022)

Worked for the Zalando Premium Logistics team to develop and maintain systems for same-day, next-day, and B2B deliveries. Also, extended support for return pick-ups of Zalando orders.

=== Redmart
==== Sr. Software Engineer (2018 - 2020)
Designed and implemented a fulfillment system for SEA groceries using Scala, Play, MongoDB.

Utilized event sourcing and domain-driven development with Akka streams, RabbitMQ to build scalable, maintainable system

Steering merger of Redmart fulfillment tech with Lazada post Alibaba acquisition

=== Soci茅t茅 G茅n茅rale
==== Tech Lead
Steering the initiative to migrate the monolithic application to a microservices architecture, using Java, Spring Boot, and PostgreSQL.

Contributed to company-wide digital transformation initiative using Docker on private cloud, improving scalability and reliability; https://sysdig.com/wp-content/uploads/2019/01/societe-generale-case-study.pdf[case study]

=== Google
==== Lead Software Engineer

Designed and implemented APIs, data analytics platforms, monitoring and alerting platforms for digital marketing.

Utilized MapReduce, BigTable, MegaStore and Google Cloud Spanner to implement data pipelines of advertising metrics.

Led the containerization and deployment of applications using Borg (Kubernetes today, resulting in improved reliability and ease of deployment.

=== Tata Consultancy Services
==== Software Engineer

== Skills & Knowledge

Specialising in developing open source software related to the development, deployment, monitoring and management of
internet facing software. List of competencies include:

[cols="2,8"]
|===
h| Programming Languages    | Kotlin 路 Java 路 Python 路 Golang 路 TypeScript 路 JavaScript
h| Frameworks               | SpringBoot 路 Play 路 AkkaStreams
h| Infrastructure           | Docker 路 Kubernetes 路 Virtualbox 路 NGINX 路 Apache HTTP 路 Docker Compose 路 TravisCI 路 Jenkins
h| Monitoring               | DataDog 路 Logstash 路 Elasticsearch 路 Kibana 路 Grafana
h| Testing                  | Locust 路 Vegeta
h| Network Protocols        | HTTP/1.1 路 HTTP/2 路 TCP 路 UDP 路 TLS/SSL
h| Cloud Services           | AWS 路 Google Cloud
|===

<<<
== References

TODO: Should add all the references/papers/whatever

bibliography::[]
