= Gunjan Patel
:icons: font
:docinfo: private-head

// Google Analytics
ifdef::backend-html5[]
++++
include::ga.html[]
++++
endif::[]

// Crosslinking
ifdef::backend-pdf[]
TIP: This resume is being regularly updated. An up to date copy is available in HTML at
     https://www.actuallygunjan.com[www.actuallygunjan.com][the same website] or via downloadable PDF on .
endif::[]

ifdef::backend-html5[]
TIP: This resume is being regularly updated. However a printable PDF copy of the current version of this resume can be
     found https://www.actuallygunjan.com/media/pdf/resume.pdf[attached to this website].
endif::[]

NOTE: Looking to embark myself on Web3 (or whatever you'd like to call it) - Crypto stuff
I may not be a stand-up comedian, but I am a stand-out software engineer who happens to be a passionate techie.

== Personal Information

[cols="3,8,3,8"]
|===
h| Email     | mailto:deago.gunjan@gmail.com[deago.gunjan@gmail.com]                                  h| GitHub    | https://www.github.com/actuallygunjan/[@actuallygunjan]
h| Telephone |  +49 174 2585884                                                                     h| LinkedIn  | https://www.linkedin.com/in/actuallygunjan/[actuallygunjan]
h| Website   | https://github.com/actuallygunjan/actuallygunjan.github.io[www.actuallygunjan.com]     h| Twitter   | https://www.twitter.com/@actuallygunjan[@actuallygunjan]
|===

== Professional Background

=== N26 Bank

// .3+<.>m|Write whatever

[cols="2,3,5"]
|===
h| Dates    | 2022 - Present            .3+<.>|
Building KYC backends for N26, integrating systems with multiple KYC providers for various markets.
Building a self-organizing team, partially fulfilling the role of engineering manager
h| Location | Berlin, Germany (Hybrid)
h| Role     | Sr. Software Engineer
|===

=== Zalando SE

[cols="3,8"]
|===
h| Dates    | December 2019 - 2021
h| Location | Berlin, Germany (Hybrid)
h| Role     | Software Engineer
|===

- Worked for the Zalando Premium Logistics team to develop and maintain systems for same-day, next-day, and B2B deliveries. Also, extended support for return pick-ups of Zalando orders.
- Contributed to the development of open-source APIs using [Zalando's API guidelines](https://opensource.zalando.com/restful-api-guidelines/). Also integrated systems with a third-party SaaS provider [Tiramizoo](https://tiramizoo.com/en/) (and others) with additional features.
- Utilized Locust and [Vegeta](https://github.com/tsenart/vegeta) for load-testing and performance optimization for the popular Zalando cyber-week sale.

=== Redmart

[cols="3,8"]
|===
h|Dates     | 2018 - 2020
h|Location  | Bengaluru, India
h| Role     | Senior Software Engineer
|===

- Designed and implemented a fulfillment system for SEA groceries using Scala, Play, MongoDB
- Utilized event sourcing and domain-driven development with Akka streams, RabbitMQ to build scalable, maintainable system
- Steering merger of Redmart fulfillment tech with Lazada post Alibaba acquisition

=== Soci茅t茅 G茅n茅rale

[cols="3,8"]
|===
h| Dates    | 2017 - 2018
h| Location | Bengaluru, India
h| Role     | Tech lead
|===

- Steering the initiative to migrate the monolithic application to a microservices architecture, using Java, Spring Boot, and PostgreSQL.
- Contributed to company-wide digital transformation initiative using Docker on private cloud, improving scalability and reliability (case study: [https://sysdig.com/wp-content/uploads/2019/01/societe-generale-case-study.pdf](https://sysdig.com/wp-content/uploads/2019/01/societe-generale-case-study.pdf)).

=== Google

[cols="3,8"]
|===
h| Dates    | 2013 - 2016
h| Location | Hyderabad, India
h| Role     | Lead Software Engineer
|===

=== Tata Consultancy Services

[cols="3,8"]
|===
h| Dates    | 2011 - 2013
h| Location | Ahmedabad, India
h| Role     | Software Engineer
|===

Write something about TCS here.

==== Achievements

- Achievement 1
- Achievement 2

<<<
== Skills & Knowledge

Specialising in developing open source software related to the development, deployment, monitoring and management of
internet facing software. List of competencies include:

[cols="2,8"]
|===
h| Software Languages | Kotlin 路 Java 路 Python 路 HTML 路 CSS 路 SASS 路 Bash 路 ECMAScript (JavaScript) 路 Golang 路 路 Make 路 Ruby 路
                        JSON+LD 路 RDFa 路 sh 路 SQL
h| Frameworks         | Magento 路 Laravel 路 Symfony 路 Joolma 路 Hugo 路 Bootstrap 路 PostCSS 路 Phing 路 Grunt 路 Polymer 路
                        RequireJS 路 Composer 路 Bower
h| Operating Systems  | Linux 路 Windows 路 Debian 路 Ubuntu 路 CentOS 路 Arch 路 CoreOS
h| Infrastructure     | Docker 路 Kubernetes 路Virtualbox 路 NGINX 路 Apache HTTP 路 Docker Compose 路 Calico 路
                        Flannel 路 TravisCI 路 Jenkins 路 Netcat 路 Tcpdump 路 cURL 路 Aptitude 路Yum 路 Picfit
h| Monitoring         | Datadog 路 Logstash 路 Elasticsearch 路 Kibana 路 Grafana
h| Testing            | Locust 路 Vegeta
h| Website Analysis   | Google Analytics 路 Chrome DevTools 路 Lighthouse 路 Google PageSpeed Insights 路 Qualsys SSL Test
h| Network Protocols  | HTTP/1.1 路 HTTP/2 路 TCP 路 UDP 路 TLS/SSL
h| Cloud Services     | AWS 路 Google Cloud
h| Security           | Pass 路 PGP 路GnuPG 路 OpenSSL 路 HSTS 路 CSP 路 Nmap
|===

<<<
== References

TODO: Should add all the references/papers/whatever

bibliography::[]
