= Gunjan Patel
:icons: font
:docinfo: private-head

// Google Analytics
ifdef::backend-html5[]
++++
include::ga.html[]
++++
endif::[]

// Crosslinking
ifdef::backend-pdf[]
TIP: This resume is being regularly updated. An up to date copy is available in HTML at 
     https://www.actuallygunjan.com[www.actuallygunjan.com] or via downloadable PDF on 
     https://www.andrewhowden.com/media/pdf/resume.pdf[the same website].
endif::[]

ifdef::backend-html5[]
TIP: This resume is being regularly updated. However a printable PDF copy of the current version of this resume can be 
     found https://www.andrewhowden.com/media/pdf/resume.pdf[attached to this website].
endif::[]

CAUTION: Looking to embark myself on Web3 (or whatever you'd like to call it) - Crypto stuff
I may not be a stand-up comedian, but I am a stand-out software engineer who happens to be a passionate techie. 

== Personal Information

[cols="3,8,3,8"]
|===
h| Email     | mailto:deago.gunjan@gmail.com[deago.gunjan@gmail.com]                                  h| GitHub    | https://www.github.com/actuallygunjan/[@actuallygunjan]
h| Telephone |  +49 174 2585884                                                                     h| LinkedIn  | https://www.linkedin.com/in/actuallygunjan/[actuallygunjan]
h| Website   | https://github.com/actuallygunjan/actuallygunjan.github.io[www.actuallygunjan.com]     h| Twitter   | https://www.twitter.com/@actuallygunjan[@actuallygunjan]
|===

== Professional Background

=== N26

[cols="3,8"]
|===
h| Dates    | 2022 - Present
h| Location | Berlin, Germany (Hybrid)
h| Role     | Senior Software Engineer
|===

=== Zalando SE

[cols="3,8"]
|===
h| Dates    | December 2019 - 2021
h| Location | Berlin, Germany (Hybrid)
h| Role     | Software Engineer
|===

=== Redmart

[cols="3,8"]
|===
h|Dates     | 2018 - 2020
h|Location  | Bengaluru, India
h| Role     | Senior Software Engineer
|===

=== Soci茅t茅 G茅n茅rale

[cols="3,8"]
|===
h| Dates    | 2017 - 2018
h| Location | Bengaluru, India
h| Role     | Tech lead
|===

=== Google

[cols="3,8"]
|===
h| Dates    | 2013 - 2016
h| Location | Hyderabad, India
h| Role     | Lead Software Engineer
|===

=== Tata Consultancy Services

[cols="3,8"]
|===
h| Dates    | 2011 - 2013
h| Location | Ahmedabad, India
h| Role     | Software Engineer
|===

Write something about TCS here.

==== Achievements

- Achievement 1
- Achievement 2

<<<
== Skills & Knowledge

Specialising in developing open source software related to the development, deployment, monitoring and management of 
internet facing software. List of competencies include:

[cols="2,8"]
|===
h| Software Languages | Java 路 HTML 路 CSS 路 SASS 路 Bash 路 ECMAScript (JavaScript) 路 Golang 路 Python 路 Make 路 Ruby 路 
                        JSON+LD 路 RDFa 路 sh 路 SQL
h| Frameworks         | Magento 路 Laravel 路 Symfony 路 Joolma 路 Hugo 路 Bootstrap 路 PostCSS 路 Phing 路 Grunt 路 Polymer 路 
                        RequireJS 路 Composer 路 Bower
h| Operating Systems  | Linux 路 Windows 路 Debian 路 Ubuntu 路 CentOS 路 Arch 路 CoreOS
h| Infrastructure     | Docker 路 Rkt 路 Kubernetes 路Virtualbox 路 NGINX 路 Apache HTTP 路 Docker Compose 路 Calico 路 
                        Flannel 路 TravisCI 路 Jenkins 路 Netcat 路 Tcpdump 路 cURL 路 Aptitude 路Yum 路 Picfit
h| Monitoring         | Prometheus 路 Sensu 路 Logstash 路 Beats 路 Elasticsearch 路 Kibana 路 Grafana
h| Testing            | Selenium 路 Facebook Web Driver 路 PHPUnit
h| Software Analysis  | PHP 路 PHPCS 路 eslint 路 scss-lint 路 jsonlint
h| Website Analysis   | Google Analytics 路 Chrome DevTools 路 Lighthouse 路 Google PageSpeed Insights 路 Qualsys SSL Test
h| Network Protocols  | HTTP/1.1 路 HTTP/2 路 FastCGI 路 TCP 路 UDP 路 TLS/SSL
h| Cloud Services     | Amazon Web Services 路 Google Cloud 路 Lets Encrypt
h| Security           | Pass 路 PGP 路GnuPG 路 OpenSSL 路 HSTS 路 CSP 路 Nmap
h| Development        | Boilr 路 Intellij IDEs 路 Atom 路 Git 路 Arcanist 路 Phabricator 路 GitHub 路 Request Tracker 路 Modd 路 
                        strace 路 strings 路 xdebug 路 xdd
|===

<<<
== References

bibliography::[]
